/**
 * THIS MODULE IS VERY INCOMPLETE, ANY CODE RELYING ON IT WILL NOT WORK IN FUTURE VERSIONS
 * The optional value parser that parses values of different systemd values
 * The configuration keys and functions systemd uses can be found at:
 * https://github.com/systemd/systemd/blob/main/src/core/load-fragment-gperf.gperf.in
 * https://github.com/systemd/systemd/blob/main/src/shared/conf-parser.c
 * systemd commit: 5f0d98e7285a612366169690ff11abdd46ba9ad2
 * podman commit: 010e7ce5567af7e55eca71c9c9436ab44470cc00
 */

import { ValueParser } from "./valueparser.js";

type ParserFunc = (value: string) => any;

function systemd(
  parser: ValueParser,
  { have_seccomp = true, have_pam = true, have_selinux = true, have_apparmor = true, enable_smack = true } = {},
): Record<string, Record<string, ParserFunc | null>> {
  const commonExecItems: Record<string, ParserFunc> = {
    WorkingDirectory: parser.working_directory,
    RootDirectory: parser.unit_path_printf, // true,
    RootImage: parser.unit_path_printf, // true,
    RootImageOptions: parser.root_image_options,
    RootImagePolicy: parser.image_policy,
    RootHash: parser.exec_root_hash,
    RootHashSignature: parser.exec_root_hash_sig,
    RootVerity: parser.unit_path_printf, // true,
    RootEphemeral: parser.bool,
    RootMStack: parser.unit_path_printf, // true,
    ExtensionDirectories: parser.namespace_path_strv,
    ExtensionImages: parser.extension_images,
    ExtensionImagePolicy: parser.image_policy,
    MountImages: parser.mount_images,
    MountImagePolicy: parser.image_policy,
    User: parser.user_group_compat,
    Group: parser.user_group_compat,
    SupplementaryGroups: parser.user_group_strv_compat,
    SetLoginEnvironment: parser.tristate,
    Nice: parser.exec_nice,
    OOMScoreAdjust: parser.exec_oom_score_adjust,
    CoredumpFilter: parser.exec_coredump_filter,
    IOSchedulingClass: parser.exec_io_class,
    IOSchedulingPriority: parser.exec_io_priority,
    CPUSchedulingPolicy: parser.exec_cpu_sched_policy,
    CPUSchedulingPriority: parser.exec_cpu_sched_prio,
    CPUSchedulingResetOnFork: parser.bool,
    CPUAffinity: parser.exec_cpu_affinity,
    NUMAPolicy: parser.numa_policy,
    NUMAMask: parser.numa_mask,
    UMask: parser.mode,
    Environment: parser.environ,
    EnvironmentFile: parser.unit_env_file,
    PassEnvironment: parser.pass_environ,
    UnsetEnvironment: parser.unset_environ,
    DynamicUser: parser.bool, // true,
    RemoveIPC: parser.bool,
    StandardInput: parser.exec_input,
    StandardOutput: parser.exec_output,
    StandardError: parser.exec_output,
    StandardInputText: parser.exec_input_text,
    StandardInputData: parser.exec_input_data,
    TTYPath: parser.unit_path_printf,
    TTYReset: parser.bool,
    TTYVHangup: parser.bool,
    TTYVTDisallocate: parser.bool,
    TTYRows: parser.tty_size,
    TTYColumns: parser.tty_size,
    SyslogIdentifier: parser.unit_string_printf,
    SyslogFacility: parser.log_facility,
    SyslogLevel: parser.log_level,
    SyslogLevelPrefix: parser.bool,
    LogLevelMax: parser.log_level,
    LogRateLimitIntervalSec: parser.sec,
    LogRateLimitBurst: parser.unsigned,
    LogExtraFields: parser.log_extra_fields,
    LogFilterPatterns: parser.log_filter_patterns,
    Capabilities: () => parser.warn_compat("DISABLED_LEGACY"),
    SecureBits: parser.exec_secure_bits,
    CapabilityBoundingSet: parser.capability_set,
    AmbientCapabilities: parser.capability_set,
    TimerSlackNSec: parser.nsec,
    NoNewPrivileges: parser.bool,
    KeyringMode: parser.exec_keyring_mode,
    ProtectProc: parser.protect_proc,
    ProcSubset: parser.proc_subset,
    PrivateBPF: parser.private_bpf,
    BPFDelegateCommands: parser.bpf_delegate_commands,
    BPFDelegateMaps: parser.bpf_delegate_maps,
    BPFDelegatePrograms: parser.bpf_delegate_programs,
    BPFDelegateAttachments: parser.bpf_delegate_attachments,
    SystemCallFilter: have_seccomp ? parser.syscall_filter : () => parser.warn_compat("DISABLED_CONFIGURATION"),
    SystemCallArchitectures: have_seccomp ? parser.syscall_archs : () => parser.warn_compat("DISABLED_CONFIGURATION"),
    SystemCallErrorNumber: have_seccomp ? parser.syscall_errno : () => parser.warn_compat("DISABLED_CONFIGURATION"),
    SystemCallLog: have_seccomp ? parser.syscall_log : () => parser.warn_compat("DISABLED_CONFIGURATION"),
    MemoryDenyWriteExecute: have_seccomp ? parser.bool : () => parser.warn_compat("DISABLED_CONFIGURATION"),
    RestrictNamespaces: have_seccomp ? parser.namespace_flags : () => parser.warn_compat("DISABLED_CONFIGURATION"),
    RestrictRealtime: have_seccomp ? parser.bool : () => parser.warn_compat("DISABLED_CONFIGURATION"),
    RestrictSUIDSGID: have_seccomp ? parser.bool : () => parser.warn_compat("DISABLED_CONFIGURATION"),
    RestrictAddressFamilies: have_seccomp
      ? parser.address_families
      : () => parser.warn_compat("DISABLED_CONFIGURATION"),
    LockPersonality: have_seccomp ? parser.bool : () => parser.warn_compat("DISABLED_CONFIGURATION"),
    DelegateNamespaces: parser.namespace_flags,
    RestrictFileSystems: parser.restrict_filesystems,
    LimitCPU: parser.rlimit, // RLIMIT_CPU,
    LimitFSIZE: parser.rlimit, // RLIMIT_FSIZE,
    LimitDATA: parser.rlimit, // RLIMIT_DATA,
    LimitSTACK: parser.rlimit, // RLIMIT_STACK,
    LimitCORE: parser.rlimit, // RLIMIT_CORE,
    LimitRSS: parser.rlimit, // RLIMIT_RSS,
    LimitNOFILE: parser.rlimit, // RLIMIT_NOFILE,
    LimitAS: parser.rlimit, // RLIMIT_AS,
    LimitNPROC: parser.rlimit, // RLIMIT_NPROC,
    LimitMEMLOCK: parser.rlimit, // RLIMIT_MEMLOCK,
    LimitLOCKS: parser.rlimit, // RLIMIT_LOCKS,
    LimitSIGPENDING: parser.rlimit, // RLIMIT_SIGPENDING,
    LimitMSGQUEUE: parser.rlimit, // RLIMIT_MSGQUEUE,
    LimitNICE: parser.rlimit, // RLIMIT_NICE,
    LimitRTPRIO: parser.rlimit, // RLIMIT_RTPRIO,
    LimitRTTIME: parser.rlimit, // RLIMIT_RTTIME,
    ReadWriteDirectories: parser.namespace_path_strv,
    ReadOnlyDirectories: parser.namespace_path_strv,
    InaccessibleDirectories: parser.namespace_path_strv,
    ReadWritePaths: parser.namespace_path_strv,
    ReadOnlyPaths: parser.namespace_path_strv,
    InaccessiblePaths: parser.namespace_path_strv,
    ExecPaths: parser.namespace_path_strv,
    NoExecPaths: parser.namespace_path_strv,
    ExecSearchPath: parser.colon_separated_paths,
    BindPaths: parser.bind_paths,
    BindReadOnlyPaths: parser.bind_paths,
    TemporaryFileSystem: parser.temporary_filesystems,
    PrivateTmp: parser.private_tmp,
    PrivateDevices: parser.bool,
    ProtectKernelTunables: parser.bool,
    ProtectKernelModules: parser.bool,
    ProtectKernelLogs: parser.bool,
    ProtectClock: parser.bool,
    ProtectControlGroups: parser.protect_control_groups,
    UserNamespacePath: parser.unit_path_printf,
    NetworkNamespacePath: parser.unit_path_printf,
    IPCNamespacePath: parser.unit_path_printf,
    LogNamespace: parser.log_namespace,
    PrivateNetwork: parser.bool,
    PrivateUsers: parser.private_users,
    PrivateMounts: parser.tristate,
    PrivateIPC: parser.bool,
    PrivatePIDs: parser.private_pids,
    ProtectSystem: parser.protect_system,
    ProtectHome: parser.protect_home,
    MountFlags: parser.exec_mount_propagation_flag,
    MountAPIVFS: parser.tristate,
    BindLogSockets: parser.tristate,
    Personality: parser.personality,
    RuntimeDirectoryPreserve: parser.exec_preserve_mode,
    RuntimeDirectoryMode: parser.mode,
    RuntimeDirectory: parser.exec_directories,
    StateDirectoryMode: parser.mode,
    StateDirectoryAccounting: parser.bool,
    StateDirectoryQuota: parser.exec_quota,
    StateDirectory: parser.exec_directories,
    CacheDirectoryMode: parser.mode,
    CacheDirectoryAccounting: parser.bool,
    CacheDirectoryQuota: parser.exec_quota,
    CacheDirectory: parser.exec_directories,
    LogsDirectoryMode: parser.mode,
    LogsDirectoryAccounting: parser.bool,
    LogsDirectoryQuota: parser.exec_quota,
    LogsDirectory: parser.exec_directories,
    ConfigurationDirectoryMode: parser.mode,
    ConfigurationDirectory: parser.exec_directories,
    SetCredential: parser.set_credential,
    SetCredentialEncrypted: parser.set_credential, // 1,
    LoadCredential: parser.load_credential,
    LoadCredentialEncrypted: parser.load_credential, // 1,
    ImportCredential: parser.import_credential,
    TimeoutCleanSec: parser.sec,
    PAMName: have_pam ? parser.unit_string_printf : () => parser.warn_compat("DISABLED_CONFIGURATION"),
    IgnoreSIGPIPE: parser.bool,
    UtmpIdentifier: parser.unit_string_printf,
    UtmpMode: parser.exec_utmp_mode,
    SELinuxContext: have_selinux ? parser.exec_selinux_context : () => parser.warn_compat("DISABLED_CONFIGURATION"),
    AppArmorProfile: have_apparmor ? parser.exec_apparmor_profile : () => parser.warn_compat("DISABLED_CONFIGURATION"),
    SmackProcessLabel: enable_smack
      ? parser.exec_smack_process_label
      : () => parser.warn_compat("DISABLED_CONFIGURATION"),
    ProtectHostname: parser.protect_hostname,
    MemoryKSM: parser.tristate,
    MemoryTHP: parser.exec_memory_thp,
  };

  const commonKillItems: Record<string, ParserFunc> = {
    SendSIGKILL: parser.bool,
    SendSIGHUP: parser.bool,
    KillMode: parser.kill_mode,
    KillSignal: parser.signal,
    RestartKillSignal: parser.signal,
    FinalKillSignal: parser.signal,
    WatchdogSignal: parser.signal,
  };

  const commonCGroupItems: Record<string, ParserFunc> = {
    Slice: parser.unit_slice,
    AllowedCPUs: parser.unit_cpu_set,
    StartupAllowedCPUs: parser.unit_cpu_set,
    AllowedMemoryNodes: parser.unit_cpu_set,
    StartupAllowedMemoryNodes: parser.unit_cpu_set,
    CPUSetPartition: parser.cpuset_partition,
    CPUAccounting: () => parser.warn_compat("DISABLED_LEGACY"),
    CPUWeight: parser.cg_cpu_weight,
    StartupCPUWeight: parser.cg_cpu_weight,
    CPUShares: () => parser.warn_compat("DISABLED_LEGACY"),
    StartupCPUShares: () => parser.warn_compat("DISABLED_LEGACY"),
    CPUQuota: parser.cpu_quota,
    CPUQuotaPeriodSec: parser.sec_def_infinity,
    MemoryAccounting: parser.bool,
    MemoryMin: parser.memory_limit,
    MemoryLow: parser.memory_limit,
    StartupMemoryLow: parser.memory_limit,
    DefaultMemoryMin: () => parser.warn_compat("DISABLED_LEGACY"),
    DefaultMemoryLow: () => parser.warn_compat("DISABLED_LEGACY"),
    DefaultStartupMemoryLow: () => parser.warn_compat("DISABLED_LEGACY"),
    MemoryHigh: parser.memory_limit,
    StartupMemoryHigh: parser.memory_limit,
    MemoryMax: parser.memory_limit,
    StartupMemoryMax: parser.memory_limit,
    MemorySwapMax: parser.memory_limit,
    StartupMemorySwapMax: parser.memory_limit,
    MemoryZSwapMax: parser.memory_limit,
    StartupMemoryZSwapMax: parser.memory_limit,
    MemoryZSwapWriteback: parser.bool,
    MemoryLimit: () => parser.warn_compat("DISABLED_LEGACY"),
    DeviceAllow: parser.device_allow,
    DevicePolicy: parser.device_policy,
    IOAccounting: parser.bool,
    IOWeight: parser.cg_weight,
    StartupIOWeight: parser.cg_weight,
    IODeviceWeight: parser.io_device_weight,
    IOReadBandwidthMax: parser.io_limit,
    IOWriteBandwidthMax: parser.io_limit,
    IOReadIOPSMax: parser.io_limit,
    IOWriteIOPSMax: parser.io_limit,
    IODeviceLatencyTargetSec: parser.io_device_latency,
    BlockIOAccounting: () => parser.warn_compat("DISABLED_LEGACY"),
    BlockIOWeight: () => parser.warn_compat("DISABLED_LEGACY"),
    StartupBlockIOWeight: () => parser.warn_compat("DISABLED_LEGACY"),
    BlockIODeviceWeight: () => parser.warn_compat("DISABLED_LEGACY"),
    BlockIOReadBandwidth: () => parser.warn_compat("DISABLED_LEGACY"),
    BlockIOWriteBandwidth: () => parser.warn_compat("DISABLED_LEGACY"),
    TasksAccounting: parser.bool,
    TasksMax: parser.tasks_max,
    Delegate: parser.delegate,
    DelegateSubgroup: parser.delegate_subgroup,
    DisableControllers: parser.disable_controllers,
    IPAccounting: parser.bool,
    IPAddressAllow: parser.in_addr_prefixes, // AF_UNSPEC,
    IPAddressDeny: parser.in_addr_prefixes, // AF_UNSPEC,
    IPIngressFilterPath: parser.ip_filter_bpf_progs,
    IPEgressFilterPath: parser.ip_filter_bpf_progs,
    ManagedOOMSwap: parser.managed_oom_mode,
    ManagedOOMMemoryPressure: parser.managed_oom_mode,
    ManagedOOMMemoryPressureLimit: parser.managed_oom_mem_pressure_limit,
    ManagedOOMMemoryPressureDurationSec: parser.managed_oom_mem_pressure_duration_sec,
    ManagedOOMPreference: parser.managed_oom_preference,
    OOMRules: parser.managed_oom_rules, // 1,
    NetClass: () => parser.warn_compat("DISABLED_LEGACY"),
    BPFProgram: parser.bpf_foreign_program,
    SocketBindAllow: parser.cgroup_socket_bind,
    SocketBindDeny: parser.cgroup_socket_bind,
    RestrictNetworkInterfaces: parser.restrict_network_interfaces,
    MemoryPressureThresholdSec: parser.sec,
    MemoryPressureWatch: parser.pressure_watch,
    CPUPressureThresholdSec: parser.sec,
    CPUPressureWatch: parser.pressure_watch,
    IOPressureThresholdSec: parser.sec,
    IOPressureWatch: parser.pressure_watch,
    NFTSet: parser.cgroup_nft_set, // NFT_SET_PARSE_CGROUP,
    CoredumpReceive: parser.bool,
    BindNetworkInterface: parser.bind_network_interface,
  };

  return {
    Unit: {
      Description: parser.unit_string_printf,
      Documentation: parser.documentation,
      SourcePath: parser.unit_path_printf,
      Requires: parser.unit_deps, // UNIT_REQUIRES,
      Requisite: parser.unit_deps, // UNIT_REQUISITE,
      Wants: parser.unit_deps, // UNIT_WANTS,
      BindsTo: parser.unit_deps, // UNIT_BINDS_TO,
      BindTo: parser.unit_deps, // UNIT_BINDS_TO,
      Upholds: parser.unit_deps, // UNIT_UPHOLDS,
      Conflicts: parser.unit_deps, // UNIT_CONFLICTS,
      Before: parser.unit_deps, // UNIT_BEFORE,
      After: parser.unit_deps, // UNIT_AFTER,
      OnSuccess: parser.unit_deps, // UNIT_ON_SUCCESS,
      OnFailure: parser.unit_deps, // UNIT_ON_FAILURE,
      PropagatesReloadTo: parser.unit_deps, // UNIT_PROPAGATES_RELOAD_TO,
      PropagateReloadTo: parser.unit_deps, // UNIT_PROPAGATES_RELOAD_TO,
      ReloadPropagatedFrom: parser.unit_deps, // UNIT_RELOAD_PROPAGATED_FROM,
      PropagateReloadFrom: parser.unit_deps, // UNIT_RELOAD_PROPAGATED_FROM,
      PropagatesStopTo: parser.unit_deps, // UNIT_PROPAGATES_STOP_TO,
      StopPropagatedFrom: parser.unit_deps, // UNIT_STOP_PROPAGATED_FROM,
      PartOf: parser.unit_deps, // UNIT_PART_OF,
      JoinsNamespaceOf: parser.unit_deps, // UNIT_JOINS_NAMESPACE_OF,
      RequiresOverridable: parser.obsolete_unit_deps, // UNIT_REQUIRES,
      RequisiteOverridable: parser.obsolete_unit_deps, // UNIT_REQUISITE,
      RequiresMountsFor: parser.unit_mounts_for,
      WantsMountsFor: parser.unit_mounts_for,
      StopWhenUnneeded: parser.bool,
      RefuseManualStart: parser.bool,
      RefuseManualStop: parser.bool,
      AllowIsolate: parser.bool,
      DefaultDependencies: parser.bool,
      SurviveFinalKillSignal: parser.bool,
      OnSuccessJobMode: parser.job_mode,
      OnFailureJobMode: parser.job_mode,
      // legacy alias
      OnFailureIsolate: parser.job_mode_isolate,
      IgnoreOnIsolate: parser.bool,
      IgnoreOnSnapshot: () => parser.warn_compat("DISABLED_LEGACY"),
      JobTimeoutSec: parser.job_timeout_sec,
      JobRunningTimeoutSec: parser.job_running_timeout_sec,
      JobTimeoutAction: parser.emergency_action,
      JobTimeoutRebootArgument: parser.reboot_parameter,
      StartLimitIntervalSec: parser.sec,
      // legacy alias
      StartLimitInterval: parser.sec,
      StartLimitBurst: parser.unsigned,
      StartLimitAction: parser.emergency_action,
      FailureAction: parser.emergency_action,
      SuccessAction: parser.emergency_action,
      FailureActionExitStatus: parser.exit_status,
      SuccessActionExitStatus: parser.exit_status,
      RebootArgument: parser.reboot_parameter,
      ConditionPathExists: parser.unit_condition_path, // CONDITION_PATH_EXISTS,
      ConditionPathExistsGlob: parser.unit_condition_path, // CONDITION_PATH_EXISTS_GLOB,
      ConditionPathIsDirectory: parser.unit_condition_path, // CONDITION_PATH_IS_DIRECTORY,
      ConditionPathIsSymbolicLink: parser.unit_condition_path, // CONDITION_PATH_IS_SYMBOLIC_LINK,
      ConditionPathIsMountPoint: parser.unit_condition_path, // CONDITION_PATH_IS_MOUNT_POINT,
      ConditionPathIsReadWrite: parser.unit_condition_path, // CONDITION_PATH_IS_READ_WRITE,
      ConditionPathIsEncrypted: parser.unit_condition_path, // CONDITION_PATH_IS_ENCRYPTED,
      ConditionPathIsSocket: parser.unit_condition_path, // CONDITION_PATH_IS_SOCKET,
      ConditionDirectoryNotEmpty: parser.unit_condition_path, // CONDITION_DIRECTORY_NOT_EMPTY,
      ConditionFileNotEmpty: parser.unit_condition_path, // CONDITION_FILE_NOT_EMPTY,
      ConditionFileIsExecutable: parser.unit_condition_path, // CONDITION_FILE_IS_EXECUTABLE,
      ConditionNeedsUpdate: parser.unit_condition_path, // CONDITION_NEEDS_UPDATE,
      ConditionFirstBoot: parser.unit_condition_string, // CONDITION_FIRST_BOOT,
      ConditionArchitecture: parser.unit_condition_string, // CONDITION_ARCHITECTURE,
      ConditionFirmware: parser.unit_condition_string, // CONDITION_FIRMWARE,
      ConditionVirtualization: parser.unit_condition_string, // CONDITION_VIRTUALIZATION,
      ConditionHost: parser.unit_condition_string, // CONDITION_HOST,
      ConditionFraction: parser.unit_condition_string, // CONDITION_FRACTION,
      ConditionKernelCommandLine: parser.unit_condition_string, // CONDITION_KERNEL_COMMAND_LINE,
      ConditionKernelVersion: parser.unit_condition_string, // CONDITION_VERSION,
      ConditionVersion: parser.unit_condition_string, // CONDITION_VERSION,
      ConditionCredential: parser.unit_condition_string, // CONDITION_CREDENTIAL,
      ConditionSecurity: parser.unit_condition_string, // CONDITION_SECURITY,
      ConditionCapability: parser.unit_condition_string, // CONDITION_CAPABILITY,
      ConditionACPower: parser.unit_condition_string, // CONDITION_AC_POWER,
      ConditionMemory: parser.unit_condition_string, // CONDITION_MEMORY,
      ConditionCPUFeature: parser.unit_condition_string, // CONDITION_CPU_FEATURE,
      ConditionCPUs: parser.unit_condition_string, // CONDITION_CPUS,
      ConditionEnvironment: parser.unit_condition_string, // CONDITION_ENVIRONMENT,
      ConditionUser: parser.unit_condition_string, // CONDITION_USER,
      ConditionGroup: parser.unit_condition_string, // CONDITION_GROUP,
      ConditionControlGroupController: parser.unit_condition_string, // CONDITION_CONTROL_GROUP_CONTROLLER
      ConditionOSRelease: parser.unit_condition_string, // CONDITION_OS_RELEASE,
      ConditionMachineTag: parser.unit_condition_string, // CONDITION_MACHINE_TAG,
      ConditionMemoryPressure: parser.unit_condition_string, // CONDITION_MEMORY_PRESSURE,
      ConditionCPUPressure: parser.unit_condition_string, // CONDITION_CPU_PRESSURE,
      ConditionIOPressure: parser.unit_condition_string, // CONDITION_IO_PRESSURE,
      ConditionKernelModuleLoaded: parser.unit_condition_string, // CONDITION_KERNEL_MODULE_LOADED,
      AssertPathExists: parser.unit_condition_path, // CONDITION_PATH_EXISTS,
      AssertPathExistsGlob: parser.unit_condition_path, // CONDITION_PATH_EXISTS_GLOB,
      AssertPathIsDirectory: parser.unit_condition_path, // CONDITION_PATH_IS_DIRECTORY,
      AssertPathIsSymbolicLink: parser.unit_condition_path, // CONDITION_PATH_IS_SYMBOLIC_LINK,
      AssertPathIsMountPoint: parser.unit_condition_path, // CONDITION_PATH_IS_MOUNT_POINT,
      AssertPathIsReadWrite: parser.unit_condition_path, // CONDITION_PATH_IS_READ_WRITE,
      AssertPathIsEncrypted: parser.unit_condition_path, // CONDITION_PATH_IS_ENCRYPTED,
      AssertPathIsSocket: parser.unit_condition_path, // CONDITION_PATH_IS_SOCKET,
      AssertDirectoryNotEmpty: parser.unit_condition_path, // CONDITION_DIRECTORY_NOT_EMPTY,
      AssertFileNotEmpty: parser.unit_condition_path, // CONDITION_FILE_NOT_EMPTY,
      AssertFileIsExecutable: parser.unit_condition_path, // CONDITION_FILE_IS_EXECUTABLE,
      AssertNeedsUpdate: parser.unit_condition_path, // CONDITION_NEEDS_UPDATE,
      AssertFirstBoot: parser.unit_condition_string, // CONDITION_FIRST_BOOT,
      AssertArchitecture: parser.unit_condition_string, // CONDITION_ARCHITECTURE,
      AssertVirtualization: parser.unit_condition_string, // CONDITION_VIRTUALIZATION,
      AssertHost: parser.unit_condition_string, // CONDITION_HOST,
      AssertFraction: parser.unit_condition_string, // CONDITION_FRACTION,
      AssertKernelCommandLine: parser.unit_condition_string, // CONDITION_KERNEL_COMMAND_LINE,
      AssertKernelVersion: parser.unit_condition_string, // CONDITION_VERSION,
      AssertVersion: parser.unit_condition_string, // CONDITION_VERSION,
      AssertCredential: parser.unit_condition_string, // CONDITION_CREDENTIAL,
      AssertSecurity: parser.unit_condition_string, // CONDITION_SECURITY,
      AssertCapability: parser.unit_condition_string, // CONDITION_CAPABILITY,
      AssertACPower: parser.unit_condition_string, // CONDITION_AC_POWER,
      AssertMemory: parser.unit_condition_string, // CONDITION_MEMORY,
      AssertCPUFeature: parser.unit_condition_string, // CONDITION_CPU_FEATURE,
      AssertCPUs: parser.unit_condition_string, // CONDITION_CPUS,
      AssertEnvironment: parser.unit_condition_string, // CONDITION_ENVIRONMENT,
      AssertUser: parser.unit_condition_string, // CONDITION_USER,
      AssertGroup: parser.unit_condition_string, // CONDITION_GROUP,
      AssertControlGroupController: parser.unit_condition_string, // CONDITION_CONTROL_GROUP_CONTROLLER
      AssertOSRelease: parser.unit_condition_string, // CONDITION_OS_RELEASE,
      AssertMachineTag: parser.unit_condition_string, // CONDITION_MACHINE_TAG,
      AssertMemoryPressure: parser.unit_condition_string, // CONDITION_MEMORY_PRESSURE,
      AssertCPUPressure: parser.unit_condition_string, // CONDITION_CPU_PRESSURE,
      AssertIOPressure: parser.unit_condition_string, // CONDITION_IO_PRESSURE,
      AssertKernelModuleLoaded: parser.unit_condition_string, // CONDITION_KERNEL_MODULE_LOADED,
      CollectMode: parser.collect_mode,
    },
    Service: {
      PIDFile: parser.pid_file,
      ExecCondition: parser.exec, // SERVICE_EXEC_CONDITION,
      ExecStartPre: parser.exec, // SERVICE_EXEC_START_PRE,
      ExecStart: parser.exec, // SERVICE_EXEC_START,
      ExecStartPost: parser.exec, // SERVICE_EXEC_START_POST,
      ExecReload: parser.exec, // SERVICE_EXEC_RELOAD,
      ExecReloadPost: parser.exec, // SERVICE_EXEC_RELOAD_POST,
      ExecStop: parser.exec, // SERVICE_EXEC_STOP,
      ExecStopPost: parser.exec, // SERVICE_EXEC_STOP_POST,
      RestartSec: parser.sec,
      RestartSteps: parser.unsigned,
      RestartMaxDelaySec: parser.sec,
      RestartRandomizedDelaySec: parser.sec,
      TimeoutSec: parser.service_timeout,
      TimeoutStartSec: parser.service_timeout,
      TimeoutStopSec: parser.sec_fix_0,
      TimeoutAbortSec: parser.service_timeout_abort,
      TimeoutStartFailureMode: parser.service_timeout_failure_mode,
      TimeoutStopFailureMode: parser.service_timeout_failure_mode,
      RuntimeMaxSec: parser.sec,
      RuntimeRandomizedExtraSec: parser.sec,
      WatchdogSec: parser.sec,
      // legacy alias, moved into unit
      StartLimitInterval: parser.sec,
      StartLimitBurst: parser.unsigned,
      StartLimitAction: parser.emergency_action,
      FailureAction: parser.emergency_action,
      RebootArgument: parser.unit_string_printf,
      Type: parser.service_type,
      ExitType: parser.service_exit_type,
      Restart: parser.service_restart,
      RestartMode: parser.service_restart_mode,
      PermissionsStartOnly: parser.bool,
      RootDirectoryStartOnly: parser.bool,
      RemainAfterExit: parser.bool,
      GuessMainPID: parser.bool,
      RestartPreventExitStatus: parser.set_status,
      RestartForceExitStatus: parser.set_status,
      SuccessExitStatus: parser.set_status,
      SysVStartPriority: () => parser.warn_compat("DISABLED_LEGACY"),
      NonBlocking: parser.bool,
      BusName: parser.bus_name,
      FileDescriptorStoreMax: parser.unsigned,
      FileDescriptorStorePreserve: parser.exec_preserve_mode,
      LUOSession: parser.luo_sessions,
      NotifyAccess: parser.notify_access,
      Sockets: parser.service_sockets,
      BusPolicy: () => parser.warn_compat("DISABLED_LEGACY"),
      USBFunctionDescriptors: parser.unit_path_printf,
      USBFunctionStrings: parser.unit_path_printf,
      OOMPolicy: parser.oom_policy,
      OpenFile: parser.open_file,
      ReloadSignal: parser.signal,
      RefreshOnReload: parser.service_refresh_on_reload,
      ...commonExecItems,
      ...commonKillItems,
      ...commonCGroupItems,
    },
    Socket: {
      ListenStream: parser.socket_listen, // SOCKET_SOCKET,
      ListenDatagram: parser.socket_listen, // SOCKET_SOCKET,
      ListenSequentialPacket: parser.socket_listen, // SOCKET_SOCKET,
      ListenFIFO: parser.socket_listen, // SOCKET_FIFO,
      ListenNetlink: parser.socket_listen, // SOCKET_SOCKET,
      ListenSpecial: parser.socket_listen, // SOCKET_SPECIAL,
      ListenMessageQueue: parser.socket_listen, // SOCKET_MQUEUE,
      ListenUSBFunction: parser.socket_listen, // SOCKET_USB_FUNCTION,
      SocketProtocol: parser.socket_protocol,
      BindIPv6Only: parser.socket_bind,
      Backlog: parser.unsigned,
      BindToDevice: parser.socket_bindtodevice,
      ExecStartPre: parser.exec, // SOCKET_EXEC_START_PRE,
      ExecStartPost: parser.exec, // SOCKET_EXEC_START_POST,
      ExecStopPre: parser.exec, // SOCKET_EXEC_STOP_PRE,
      ExecStopPost: parser.exec, // SOCKET_EXEC_STOP_POST,
      TimeoutSec: parser.sec_fix_0,
      SocketUser: parser.user_group_compat,
      SocketGroup: parser.user_group_compat,
      SocketMode: parser.mode,
      DirectoryMode: parser.mode,
      Accept: parser.bool,
      FlushPending: parser.bool,
      Writable: parser.bool,
      MaxConnections: parser.unsigned,
      MaxConnectionsPerSource: parser.unsigned,
      KeepAlive: parser.bool,
      KeepAliveTimeSec: parser.sec,
      KeepAliveIntervalSec: parser.sec,
      KeepAliveProbes: parser.unsigned,
      DeferAcceptSec: parser.sec,
      NoDelay: parser.bool,
      Priority: parser.int,
      ReceiveBuffer: parser.iec_size,
      SendBuffer: parser.iec_size,
      IPTOS: parser.ip_tos,
      IPTTL: parser.int,
      Mark: parser.int,
      PipeSize: parser.iec_size,
      FreeBind: parser.bool,
      Transparent: parser.bool,
      Broadcast: parser.bool,
      PassCredentials: parser.bool,
      PassPIDFD: parser.bool,
      PassSecurity: parser.bool,
      PassPacketInfo: parser.bool,
      AcceptFileDescriptors: parser.bool,
      Timestamping: parser.socket_timestamping,
      TCPCongestion: parser.string,
      ReusePort: parser.bool,
      MessageQueueMaxMessages: parser.long,
      MessageQueueMessageSize: parser.iec_size_long,
      RemoveOnStop: parser.bool,
      Symlinks: parser.unit_path_strv_printf,
      FileDescriptorName: parser.fdname,
      Service: parser.socket_service,
      PassFileDescriptorsToExec: parser.bool,
      TriggerLimitIntervalSec: parser.sec,
      TriggerLimitBurst: parser.unsigned,
      PollLimitIntervalSec: parser.sec,
      PollLimitBurst: parser.unsigned,
      DeferTrigger: parser.socket_defer_trigger,
      DeferTriggerMaxSec: parser.sec_fix_0,
      XAttrEntryPoint: parser.xattr,
      XAttrListen: parser.xattr,
      XAttrAccept: parser.xattr,
      SmackLabel: enable_smack ? parser.unit_string_printf : () => parser.warn_compat("DISABLED_CONFIGURATION"),
      SmackLabelIPIn: enable_smack ? parser.unit_string_printf : () => parser.warn_compat("DISABLED_CONFIGURATION"),
      SmackLabelIPOut: enable_smack ? parser.unit_string_printf : () => parser.warn_compat("DISABLED_CONFIGURATION"),
      SELinuxContextFromNet: have_selinux ? parser.bool : () => parser.warn_compat("DISABLED_CONFIGURATION"),
      ...commonExecItems,
      ...commonKillItems,
      ...commonCGroupItems,
    },
    Mount: {
      What: parser.mount_node,
      Where: parser.unit_path_printf,
      Options: parser.unit_string_printf,
      Type: parser.unit_string_printf,
      TimeoutSec: parser.sec_fix_0,
      DirectoryMode: parser.mode,
      SloppyOptions: parser.bool,
      LazyUnmount: parser.bool,
      ForceUnmount: parser.bool,
      ReadWriteOnly: parser.bool,
      ...commonExecItems,
      ...commonKillItems,
      ...commonCGroupItems,
    },
    Automount: {
      Where: parser.unit_path_printf,
      ExtraOptions: parser.unit_string_printf,
      DirectoryMode: parser.mode,
      TimeoutIdleSec: parser.sec_fix_0,
    },
    Swap: {
      What: parser.mount_node,
      Priority: parser.swap_priority,
      Options: parser.unit_string_printf,
      TimeoutSec: parser.sec_fix_0,
      ...commonExecItems,
      ...commonKillItems,
      ...commonCGroupItems,
    },
    Timer: {
      OnCalendar: parser.timer, // TIMER_CALENDAR,
      OnActiveSec: parser.timer, // TIMER_ACTIVE,
      OnBootSec: parser.timer, // TIMER_BOOT,
      OnStartupSec: parser.timer, // TIMER_STARTUP,
      OnUnitActiveSec: parser.timer, // TIMER_UNIT_ACTIVE,
      OnUnitInactiveSec: parser.timer, // TIMER_UNIT_INACTIVE,
      OnClockChange: parser.bool,
      OnTimezoneChange: parser.bool,
      Persistent: parser.bool,
      WakeSystem: parser.bool,
      RemainAfterElapse: parser.bool,
      FixedRandomDelay: parser.bool,
      DeferReactivation: parser.bool,
      AccuracySec: parser.sec,
      RandomizedDelaySec: parser.sec,
      RandomizedOffsetSec: parser.sec,
      Unit: parser.trigger_unit,
    },
    Path: {
      PathExists: parser.path_spec,
      PathExistsGlob: parser.path_spec,
      PathChanged: parser.path_spec,
      PathModified: parser.path_spec,
      DirectoryNotEmpty: parser.path_spec,
      Unit: parser.trigger_unit,
      MakeDirectory: parser.bool,
      DirectoryMode: parser.mode,
      TriggerLimitIntervalSec: parser.sec,
      TriggerLimitBurst: parser.unsigned,
    },
    Slice: {
      ConcurrencySoftMax: parser.concurrency_max,
      ConcurrencyHardMax: parser.concurrency_max,
      ActivatingConcurrencyMax: parser.concurrency_max,
      ...commonCGroupItems,
    },
    Scope: {
      ...commonCGroupItems,
      ...commonKillItems,
      RuntimeMaxSec: parser.sec,
      RuntimeRandomizedExtraSec: parser.sec,
      TimeoutStopSec: parser.sec,
      OOMPolicy: parser.oom_policy,
    },
    Install: {
      // the install secction is ignored here
      Alias: null,
      WantedBy: null,
      RequiredBy: null,
      UpheldBy: null,
      Also: null,
      DefaultInstance: null,
    },
  };
}

const quadlets = {
  Container: {
    AddCapability: true,
    AddDevice: true,
    AddHost: true,
    Annotation: true,
    AppArmor: true,
    AutoUpdate: true,
    CgroupsMode: true,
    ContainerName: true,
    ContainersConfModule: true,
    DNS: true,
    DNSOption: true,
    DNSSearch: true,
    DropCapability: true,
    Environment: true,
    EnvironmentFile: true,
    EnvironmentHost: true,
    Entrypoint: true,
    Exec: true,
    ExposeHostPort: true,
    GIDMap: true,
    GlobalArgs: true,
    Group: true,
    GroupAdd: true,
    HealthCmd: true,
    HealthInterval: true,
    HealthOnFailure: true,
    HealthLogDestination: true,
    HealthMaxLogCount: true,
    HealthMaxLogSize: true,
    HealthRetries: true,
    HealthStartPeriod: true,
    HealthStartupCmd: true,
    HealthStartupInterval: true,
    HealthStartupRetries: true,
    HealthStartupSuccess: true,
    HealthStartupTimeout: true,
    HealthTimeout: true,
    HostName: true,
    HttpProxy: true,
    IP6: true,
    IP: true,
    Image: true,
    ImageVolume: true,
    Label: true,
    LogDriver: true,
    LogOpt: true,
    Mask: true,
    Memory: true,
    Mount: true,
    Network: true,
    NetworkAlias: true,
    NoNewPrivileges: true,
    Notify: true,
    PidsLimit: true,
    Pod: true,
    PodmanArgs: true,
    PublishPort: true,
    Pull: true,
    ReadOnly: true,
    ReadOnlyTmpfs: true,
    ReloadCmd: true,
    ReloadSignal: true,
    RemapGid: true,
    RemapUid: true,
    RemapUidSize: true,
    RemapUsers: true,
    Retry: true,
    RetryDelay: true,
    Rootfs: true,
    RunInit: true,
    SeccompProfile: true,
    Secret: true,
    SecurityLabelDisable: true,
    SecurityLabelFileType: true,
    SecurityLabelLevel: true,
    SecurityLabelNested: true,
    SecurityLabelType: true,
    ServiceName: true,
    ShmSize: true,
    StopSignal: true,
    StartWithPod: true,
    StopTimeout: true,
    SubGIDMap: true,
    SubUIDMap: true,
    Sysctl: true,
    Timezone: true,
    Tmpfs: true,
    UIDMap: true,
    Ulimit: true,
    Unmask: true,
    User: true,
    UserNS: true,
    VolatileTmp: true,
    Volume: true,
    WorkingDir: true,
  },
  Volume: {
    ContainersConfModule: true,
    Copy: true,
    Device: true,
    Driver: true,
    GlobalArgs: true,
    Group: true,
    Image: true,
    Label: true,
    Options: true,
    PodmanArgs: true,
    ServiceName: true,
    Type: true,
    User: true,
    VolumeName: true,
    UID: true,
    GID: true,
  },
  Network: {
    Label: true,
    DNS: true,
    ContainersConfModule: true,
    GlobalArgs: true,
    DisableDNS: true,
    Driver: true,
    Gateway: true,
    IPAMDriver: true,
    IPRange: true,
    IPv6: true,
    InterfaceName: true,
    Internal: true,
    NetworkName: true,
    NetworkDeleteOnStop: true,
    Options: true,
    ServiceName: true,
    Subnet: true,
    PodmanArgs: true,
  },
  Kube: {
    AutoUpdate: true,
    ConfigMap: true,
    ContainersConfModule: true,
    ExitCodePropagation: true,
    GlobalArgs: true,
    KubeDownForce: true,
    LogDriver: true,
    LogOpt: true,
    Network: true,
    PodmanArgs: true,
    PublishPort: true,
    RemapGid: true,
    RemapUid: true,
    RemapUidSize: true,
    RemapUsers: true,
    ServiceName: true,
    SetWorkingDirectory: true,
    UserNS: true,
    Yaml: true,
  },
  Image: {
    AllTags: true,
    Arch: true,
    AuthFile: true,
    CertDir: true,
    ContainersConfModule: true,
    Creds: true,
    DecryptionKey: true,
    GlobalArgs: true,
    Image: true,
    ImageTag: true,
    OS: true,
    PodmanArgs: true,
    Policy: true,
    Retry: true,
    RetryDelay: true,
    ServiceName: true,
    TLSVerify: true,
    Variant: true,
  },
  Build: {
    Annotation: true,
    Arch: true,
    AuthFile: true,
    BuildArg: true,
    ContainersConfModule: true,
    DNS: true,
    DNSOption: true,
    DNSSearch: true,
    Environment: true,
    File: true,
    ForceRM: true,
    GlobalArgs: true,
    GroupAdd: true,
    IgnoreFile: true,
    ImageTag: true,
    Label: true,
    Network: true,
    PodmanArgs: true,
    Pull: true,
    Retry: true,
    RetryDelay: true,
    Secret: true,
    ServiceName: true,
    SetWorkingDirectory: true,
    Target: true,
    TLSVerify: true,
    Variant: true,
    Volume: true,
  },
  Artifact: {
    Artifact: true,
    AuthFile: true,
    CertDir: true,
    ContainersConfModule: true,
    Creds: true,
    DecryptionKey: true,
    GlobalArgs: true,
    PodmanArgs: true,
    Quiet: true,
    Retry: true,
    RetryDelay: true,
    ServiceName: true,
    TLSVerify: true,
  },
  Pod: {
    AddHost: true,
    ContainersConfModule: true,
    DNS: true,
    DNSOption: true,
    DNSSearch: true,
    ExitPolicy: true,
    GIDMap: true,
    GlobalArgs: true,
    HostName: true,
    IP: true,
    IP6: true,
    Label: true,
    Network: true,
    NetworkAlias: true,
    PodName: true,
    PodmanArgs: true,
    PublishPort: true,
    RemapGid: true,
    RemapUid: true,
    RemapUidSize: true,
    RemapUsers: true,
    ServiceName: true,
    ShmSize: true,
    StopTimeout: true,
    SubGIDMap: true,
    SubUIDMap: true,
    UIDMap: true,
    UserNS: true,
    Volume: true,
  },
  Quadlet: {
    DefaultDependencies: true,
  },
};
